// Sdílená definice polí pro modul 040 - Nemovitosti
export const FIELDS = [
  { key: 'nazev', label: 'Název nemovitosti', type: 'text', required: true },
  { key: 'typ_nemovitosti', label: 'Typ nemovitosti', type: 'select', required: true, options: [
    { value: 'bytovy_dum', label: 'Bytový dům' },
    { value: 'rodinny_dum', label: 'Rodinný dům' },
    { value: 'admin_budova', label: 'Administrativní budova' },
    { value: 'prumyslovy_objekt', label: 'Průmyslový objekt' },
    { value: 'pozemek', label: 'Pozemek' },
    { value: 'jiny_objekt', label: 'Jiný objekt' }
  ]},
  { key: 'ulice', label: 'Ulice', type: 'text' },
  { key: 'cislo_popisne', label: 'Číslo popisné', type: 'text' },
  { key: 'cislo_orientacni', label: 'Číslo orientační', type: 'text' },
  { key: 'mesto', label: 'Město', type: 'text', required: true },
  { key: 'psc', label: 'PSČ', type: 'text', pattern: '[0-9]{3}\\s?[0-9]{2}', placeholder: '123 45' },
  { key: 'kraj', label: 'Kraj', type: 'text' },
  { key: 'stat', label: 'Stát', type: 'text' },
  { key: 'pocet_podlazi', label: 'Počet podlaží', type: 'number' },
  { key: 'pocet_podzemních_podlazi', label: 'Počet podzemních podlaží', type: 'number' },
  { key: 'rok_vystavby', label: 'Rok výstavby', type: 'number', min: 1800 },
  { key: 'rok_rekonstrukce', label: 'Rok rekonstrukce', type: 'number', min: 1800 },
  { key: 'celkova_plocha', label: 'Celková plocha (m²)', type: 'number', step: '0.01' },
  { key: 'pocet_jednotek', label: 'Počet jednotek', type: 'number', readOnly: true, helpText: 'Automaticky počítané' },
  { key: 'spravce', label: 'Správce', type: 'text' },
  { key: 'pronajimatel_id', label: 'Pronajímatel', type: 'chooser', entity: 'subjects', role: 'pronajimatel', 
    buttonLabel: 'Vybrat pronajímatele', 
    displayField: 'display_name',
    helpText: 'Vyberte pronajímatele z modulu 030 (Pronajímatelé)' },
  { key: 'poznamky', label: 'Poznámka', type: 'textarea', fullWidth: true },
  { key: 'vybaveni', label: 'Vybavení', type: 'text', helpText: 'Oddělte čárkami: vytah, parkovani, kolarna, klimatizace...' },
  { key: 'prilohy', label: 'Přílohy', type: 'text', readOnly: true },
  { key: 'pronajimatel', label: 'Pronajímatel (legacy)', type: 'text', readOnly: true },
  { key: 'archived', label: 'Archivní', type: 'checkbox' },
  { key: 'archivedLabel', label: 'Archivní (text)', type: 'text', readOnly: true },
  { key: 'updated_at', label: 'Poslední úprava', type: 'label', readOnly: true },
  { key: 'updated_by', label: 'Upravil', type: 'label', readOnly: true },
  { key: 'created_at', label: 'Vytvořen', type: 'label', readOnly: true }
];
export default { FIELDS };
